## Load in Numpy 

In [1]:
import numpy as np

## The Basics

In [18]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
b.ndim

2

In [6]:
# Get shape
b.shape

(2, 3)

In [16]:
# Get type
a.dtype

dtype('int16')

In [19]:
# Get Size
a.itemsize

4

In [20]:
#Get total size
a.nbytes

12

## Accessing/Changing specific elements, rows,columns,etc


In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get a specific element [r,c]
a[1,5]


13

In [26]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [28]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [32]:
a[1,5]=20
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [34]:
#3-d example

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [41]:
#replace
b[:,1,:]=[[3,3],[4,4]]
print(b)

[[[1 2]
  [3 3]]

 [[5 6]
  [4 4]]]


## Initializing Different Types of Arrays

In [46]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# All 1s matrix
np.ones((2,3,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [54]:
# Any other number
np.full((2,3,2),99,dtype='float32')

array([[[99., 99.],
        [99., 99.],
        [99., 99.]],

       [[99., 99.],
        [99., 99.],
        [99., 99.]]], dtype=float32)

In [59]:
#Any other number(full_like)
np.full_like(a,4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [60]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.17187763, 0.0509049 ],
       [0.7740158 , 0.64436515],
       [0.95344411, 0.88896361],
       [0.79426301, 0.30645916]])

In [61]:
# input a shape
np.random.random_sample(a.shape)

array([[0.77182821, 0.55868615, 0.37874697, 0.05645929, 0.30003744,
        0.23038207, 0.62946128],
       [0.81490911, 0.96565205, 0.70220549, 0.98272286, 0.90369644,
        0.18269705, 0.76244545]])

In [70]:
#Random integer values
np.random.randint(4,8,size=(3,3))#取整数 给定范围[4,8) 给定张成尺寸

array([[4, 6, 6],
       [4, 5, 7],
       [6, 6, 7]])

In [71]:
#单位矩阵
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [97]:
tar = np.ones((5,5))
z = np.zeros((3,3))
z[1,1]=9
tar[1:-1,1:-1]=z

In [99]:
print(tar)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [103]:
a = np.array([1,2,3])
b = a.copy()#.copy--Prevent a's value from changing by b
b[0]=100
a

array([1, 2, 3])

## Mathematics

In [115]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [116]:
# a+=2
# a

In [117]:
b = np.array([1,0,1,0])
a + b 

array([2, 2, 4, 4])

In [118]:
a**2

array([ 1,  4,  9, 16])

In [127]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [139]:
a = np.ones((2,3))
b = np.full((3,2),2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [143]:
#Find the determinant(行列式)
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [151]:
stats = np.array([[1,2,3],
                  [4,5,6]])
np.min(stats)

1

In [154]:
np.max(stats,axis=1)

array([3, 6])

In [157]:
np.sum(stats,axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [162]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((2,2,2))#(2,4)(8,1)(2,2,2) 相乘结果一致即可
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [167]:
# Vertically stacking vectors(竖直堆叠向量)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2,v2,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [173]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous
#### Load data from flie

In [175]:
#file_data = np.genfromtxt('data.txt',delimiter=',')

##### Boolean masking and Advanced Indexing

In [176]:
#file_data[file_data>50]

In [182]:
## You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[a>3] #Inplace

array([4, 5, 6, 7, 8, 9])

In [183]:
np.any(a>3,axis=0)

True

In [184]:
np.all(a>3,axis=0)

False